name: gen_pdf
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  pdf: ^3.10.4
  printing: ^5.11.0
  intl: ^0.18.0
  window_manager: ^0.3.5
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  path: ^1.8.3
  uuid: ^3.0.7
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  nit_validator: ^1.0.1
  file_picker: ^5.3.2
  path_provider: ^2.0.15
  jiffy: ^6.2.1
  path_provider_windows: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.15.0

msix_config:
  display_name: Generador de facturas
  identity_name: com.reactivesoftware.genpdf
  languages: es-gt, en-us
  publisher_display_name: Brandon Manzo
  capabilities: systemManagement,appDiagnostics,runFullTrust,allowElevation,broadFileSystemAccess
  app_installer:
    publish_folder_path: C:\Users\brand\OneDrive\Escritorio\instalador
    hours_between_update_checks: 0
    automatic_background_task: false
    update_blocks_activation: false
    show_prompt: false
    force_update_from_any_version: false
  msix_version: 1.0.0.1
  build_windows: false
  certificate_path: C:\Users\brand\keys\CERTIFICATE.pfx
  certificate_password: BgcMg2802

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
    - assets/img/signature.png
